# Generated by Django 5.1.6 on 2025-03-05 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_app', '0006_hostavailability'),
        ('visitor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='host_app.hostavailability'),
        ),
    ]
