# Generated by Django 5.1.6 on 2025-03-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0002_visitor_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='meeting_time',
            new_name='meeting_start_time',
        ),
        migrations.AddField(
            model_name='visitor',
            name='meeting_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
