# Generated by Django 5.1.6 on 2025-03-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0004_alter_visitor_meeting_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='meeting_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
