# Generated by Django 5.1.6 on 2025-03-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_app', '0006_hostavailability'),
        ('visitor_app', '0005_alter_visitor_meeting_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='availability',
        ),
        migrations.AddField(
            model_name='visitor',
            name='availability',
            field=models.ManyToManyField(related_name='visitors', to='host_app.hostavailability'),
        ),
    ]
