# Generated by Django 5.1.6 on 2025-03-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0007_remove_visitor_availability_visitor_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='meeting_end_time',
            field=models.TimeField(),
        ),
    ]
