# Generated by Django 5.1.6 on 2025-04-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0008_alter_visitor_meeting_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
