# Generated by Django 5.1.6 on 2025-04-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0009_visitor_reminder_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='reminder_sent',
            new_name='reminder_for_a_day_before_meeting_sent',
        ),
        migrations.AddField(
            model_name='visitor',
            name='reminder_for_a_day_of_meeting_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='reminder_for_a_five_minute_before_meeting_sent',
            field=models.BooleanField(default=False),
        ),
    ]
