# Generated by Django 5.1.6 on 2025-03-05 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_app', '0005_remove_user_role_user_role'),
        ('visitor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_booked', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitor_app.visitor')),
            ],
        ),
    ]
